#include "stdafx.h"
#include "sort1.h"

bool Sort::flagE0=false;
bool Sort::flagE1=false;
bool Sort::flagPSUP=false;
bool Sort::flagPSDN=false;
bool Sort::flagPA1=false;
bool Sort::flagPA2=false;
bool Sort::flagPAend=false;

char* Sort::OneKeyMap[89]=\
{
	/*00*/ "",
	/*01*/ "keyboard.esc_T",
	/*02*/ "keyboard.1_T",
	/*03*/ "keyboard.2_T",
	/*04*/ "keyboard.3_T",
	/*05*/ "keyboard.4_T",
	/*06*/ "keyboard.5_T",
	/*07*/ "keyboard.6_T",
	/*08*/ "keyboard.7_T",
	/*09*/ "keyboard.8_T",
	/*0A*/ "keyboard.9_T",
	/*0B*/ "keyboard.0_T",
	/*0C*/ "keyboard.-_T",
	/*0D*/ "keyboard.=_T",
	/*0E*/ "keyboard.backspace_T",
	/*0F*/ "keyboard.tab_T",
	/*10*/ "keyboard.q_T",
	/*11*/ "keyboard.w_T",
	/*12*/ "keyboard.e_T",
	/*13*/ "keyboard.r_T",
	/*14*/ "keyboard.t_T",
	/*15*/ "keyboard.y_T",
	/*16*/ "keyboard.u_T",
	/*17*/ "keyboard.i_T",
	/*18*/ "keyboard.o_T",
	/*19*/ "keyboard.p_T",
	/*1A*/ "keyboard.[_T",
	/*1B*/ "keyboard.]_T",
	/*1C*/ "keyboard.enter_T",
	/*1D*/ "keyboard.lctrl_T",
	/*1E*/ "keyboard.a_T",
	/*1F*/ "keyboard.s_T",
	/*20*/ "keyboard.d_T",
	/*21*/ "keyboard.f_T",
	/*22*/ "keyboard.g_T",
	/*23*/ "keyboard.h_T",
	/*24*/ "keyboard.j_T",
	/*25*/ "keyboard.k_T",
	/*26*/ "keyboard.l_T",
	/*27*/ "keyboard.;_T",
	/*28*/ "keyboard.'_T",
	/*29*/ "keyboard.`_T",
	/*2A*/ "keyboard.lshift_T",
	/*2B*/ "keyboard.fxg_T",
	/*2C*/ "keyboard.z_T",
	/*2D*/ "keyboard.x_T",
	/*2E*/ "keyboard.c_T",
	/*2F*/ "keyboard.v_T",
	/*30*/ "keyboard.b_T",
	/*31*/ "keyboard.n_T",
	/*32*/ "keyboard.m_T",
	/*33*/ "keyboard.,_T",
	/*34*/ "keyboard.._T",
	/*35*/ "keyboard.xg_T",
	/*36*/ "keyboard.rshift_T",
	/*37*/ "keyboard.kp cheng_T",
	/*38*/ "keyboard.lalt_T",
	/*39*/ "keyboard.space_T",
	/*3A*/ "keyboard.lock_T",
	/*3B*/ "keyboard.f1_T",
	/*3C*/ "keyboard.f2_T",
	/*3D*/ "keyboard.f3_T",
	/*3E*/ "keyboard.f4_T",
	/*3F*/ "keyboard.f5_T",
	/*40*/ "keyboard.f6_T",
	/*41*/ "keyboard.f7_T",
	/*42*/ "keyboard.f8_T",
	/*43*/ "keyboard.f9_T",
	/*44*/ "keyboard.f10_T",
	/*45*/ "keyboard.numberlock_T",
	/*46*/ "keyboard.scrlock_T",
	/*47*/ "keyboard.kp 7_T",
	/*48*/ "keyboard.kp 8_T",
	/*49*/ "keyboard.kp 9_T",
	/*4A*/ "keyboard.kp -_T",
	/*4B*/ "keyboard.kp 4_T",
	/*4C*/ "keyboard.kp 5_T",
	/*4D*/ "keyboard.kp 6_T",
	/*4E*/ "keyboard.kp +_T",
	/*4F*/ "keyboard.kp 1_T",
	/*50*/ "keyboard.kp 2_T",
	/*51*/ "keyboard.kp 3_T",
	/*52*/ "keyboard.kp 0_T",
	/*53*/ "keyboard.kp ._T",
	/*54*/ "error",
	/*55*/ "error",
	/*56*/ "error",
	/*57*/ "keyboard.f11_T",
	/*58*/ "keyboard.f12_T",
};
char* Sort::E0name[16]=\
{
	/*52*/ "keyboard.insert_T",
	/*49*/ "keyboard.pgup_T",
	/*53*/ "keyboard.delete_T",
	/*4F*/ "keyboard.end_T",
	/*51*/ "keyboard.pgdn_T",
	/*48*/ "keyboard.shang_T",
	/*4B*/ "keyboard.zuo_T",
	/*50*/ "keyboard.xia_T",
	/*4D*/ "keyboard.you_T",
	/*5B*/ "keyboard.lwin_T",
	/*35*/ "keyboard.kp xg_T",
	/*5C*/ "keyboard.rwin_T",
	/*1D*/ "keyboard.rctrl_T",
	/*38*/ "keyboard.ralt_T",
	/*1C*/ "keyboard.kp enter_T",
	/*5D*/ "keyboard.app_T",
};
unsigned char Sort::E0value[16]=\
{
	82 /*INSERT*/,
	73 /*PG UP*/,
	83 /*DELETE*/,
	79 /*END*/,
	81 /*PG DN*/,
	72 /*U ARROW*/,
	75 /*L ARROW*/,
	80 /*D ARROW*/,
	77 /*R ARROW*/,
	91 /*L GUI*/,
	53 /*KP /*/,
	92 /*R GUI*/,
	29 /*R CTRL*/,
	56 /*R ALT*/,
	28 /*KP EN*/,
	93 /*APPS*/,
};	